### ISSUE TITLE
Updating nuetral xlf file for a updated string in resx file is failing with error "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by Faizan2304** [fmuecke/XliffParser#4]
Repro:
1) I have attached a zip file which has three file in it (Resources.resx, Resources.xlf and Resources.cs.xlf)
2) Resources.resx has two string, update the value of any string.
3) Run command "xlftool.exe update -Resx Resources.resx -Xlf Resources.xlf.
4) It will fail with error message "ERROR: Object reference not set to an instance of an object."

The above command is failing for Neutral xlf file only, the command 
"xlftool.exe update -Resx Resources.resx -Xlf Resources.cs.xlf" is working fine.

Please let me know if you need any thing from my side.

[XlfIssue.zip](https://github.com/fmuecke/XliffParser/files/673200/XlfIssue.zip)

**Comment by Faizan2304** [comment]
@fmuecke @cdmihai : Can you please take a look.

**Comment by fmuecke** [comment]
Unfortunately XliffParser does not support neutral language xlf files at the moment. Without looking more into the code I'm pretty confident that the missing (optional) `target-language` attribute is the problem here.

I'll check the code later and see what I can do.

**Comment by fmuecke** [comment]
I cannot reproduce your issue right now with version 0.1.2. What version of `xlftool.exe` did you use?

**Comment by fmuecke** [comment]
The problem had nothing to do with a missing `target-language` but with the fact that ´target´ elements may be optional.

**Comment by Raymondd** [comment]
Thanks for fixing this!
